name: Release 

run-name: Release by @${{ github.actor }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'
        preferLatestVersion: true

    - name: Determine Version
      id: version_step # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.0.0

    - name: Display GitVersion
      run: echo "FullSemVer (env.fullSemVer) ${{ env.fullSemVer }}"
    
    - name: Restore dependencies
      run: dotnet restore ./source/Serilog.Sinks.Avalonia.Browser/Serilog.Sinks.Avalonia.Browser.csproj
    
    - name: Build
      run: dotnet build ./source/Serilog.Sinks.Avalonia.Browser/Serilog.Sinks.Avalonia.Browser.csproj --no-restore --configuration Release

    - name: Pack to NuGet
      run: dotnet pack ./source/Serilog.Sinks.Avalonia.Browser/Serilog.Sinks.Avalonia.Browser.csproj --no-restore --no-build --output nupkgs -p:PackageVersion=${{ env.fullSemVer }}

    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/Serilog.Sinks.Avalonia.Browser.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_TOKEN}
      env:
        NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
